import { Wallet, TrendingUp, BarChart3, Lock, ShoppingBag } from 'lucide-react';

const formatCurrency = (amount) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', minimumFractionDigits: 2 }).format(amount);
const formatCurrencyShort = (amount) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(amount);

export const YearlySummary = ({ yearlySummary, monthlySummaries, year }) => {
  const maxValue = Math.max(...monthlySummaries.map(m => Math.max(m.income, m.expenses)), 1);
  return (
    <div className="bg-slate-800/50 border border-slate-700/50 rounded-2xl p-6 mt-6">
      <div className="flex items-center gap-3 mb-6"><div className="bg-indigo-500/20 p-2.5 rounded-xl"><BarChart3 className="w-5 h-5 text-indigo-400" /></div><h3 className="text-lg font-semibold text-white">Podsumowanie Roczne {year}</h3></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><TrendingUp className="w-4 h-4 text-emerald-400" /><span className="text-sm text-emerald-400">Przychody</span></div><p className="text-xl font-bold text-white">{formatCurrencyShort(yearlySummary.income)}</p></div>
        <div className="bg-rose-500/10 border border-rose-500/20 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><Lock className="w-4 h-4 text-rose-400" /><span className="text-sm text-rose-400">Wyd. stałe</span></div><p className="text-xl font-bold text-white">{formatCurrencyShort(yearlySummary.fixedExpenses)}</p></div>
        <div className="bg-orange-500/10 border border-orange-500/20 rounded-xl p-4"><div className="flex items-center gap-2 mb-2"><ShoppingBag className="w-4 h-4 text-orange-400" /><span className="text-sm text-orange-400">Wyd. zmienne</span></div><p className="text-xl font-bold text-white">{formatCurrencyShort(yearlySummary.variableExpenses)}</p></div>
        <div className={`${yearlySummary.balance >= 0 ? 'bg-indigo-500/10 border-indigo-500/20' : 'bg-red-500/10 border-red-500/20'} border rounded-xl p-4`}><div className="flex items-center gap-2 mb-2"><Wallet className={`w-4 h-4 ${yearlySummary.balance >= 0 ? 'text-indigo-400' : 'text-red-400'}`} /><span className={`text-sm ${yearlySummary.balance >= 0 ? 'text-indigo-400' : 'text-red-400'}`}>Bilans</span></div><p className="text-xl font-bold text-white">{formatCurrencyShort(yearlySummary.balance)}</p></div>
      </div>
      <div className="space-y-3"><h4 className="text-sm font-medium text-slate-400 mb-4">Przegląd Miesięczny</h4><div className="grid grid-cols-12 gap-2">{monthlySummaries.map((month, index) => (<div key={index} className="flex flex-col items-center"><div className="w-full h-32 flex flex-col justify-end gap-0.5"><div className="w-full bg-emerald-500/60 rounded-t-sm transition-all" style={{ height: `${(month.income / maxValue) * 100}%`, minHeight: month.income > 0 ? '4px' : '0' }} title={`Przychody: ${formatCurrency(month.income)}`} /><div className="w-full bg-rose-500/60 transition-all" style={{ height: `${(month.fixedExpenses / maxValue) * 100}%`, minHeight: month.fixedExpenses > 0 ? '2px' : '0' }} title={`Stałe: ${formatCurrency(month.fixedExpenses)}`} /><div className="w-full bg-orange-500/60 rounded-b-sm transition-all" style={{ height: `${(month.variableExpenses / maxValue) * 100}%`, minHeight: month.variableExpenses > 0 ? '2px' : '0' }} title={`Zmienne: ${formatCurrency(month.variableExpenses)}`} /></div><span className="text-xs text-slate-500 mt-2">{month.name}</span></div>))}</div><div className="flex justify-center gap-6 mt-4"><div className="flex items-center gap-2"><div className="w-3 h-3 bg-emerald-500/60 rounded" /><span className="text-xs text-slate-400">Przychody</span></div><div className="flex items-center gap-2"><div className="w-3 h-3 bg-rose-500/60 rounded" /><span className="text-xs text-slate-400">Stałe</span></div><div className="flex items-center gap-2"><div className="w-3 h-3 bg-orange-500/60 rounded" /><span className="text-xs text-slate-400">Zmienne</span></div></div></div>
    </div>
  );
};
